### ISSUE TITLE
Ubuntu 18.04: Issues with OpenConnect

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/ucsf-vpn#11]
Moving what @graft wrote in https://github.com/HenrikBengtsson/ucsf-vpn/issues/4#issuecomment-409278438 to a new issue:

An issue I have been having lately with openconnect on some of my machines is a strange name service bug - the connection looks fine, an IP is assigned, but there is no ping available (or any other IP traffic apparently). This only happens on systems that use systemd-resolved - other systems I have that still use dnsmasq seem to work okay. I haven't really been able to understand what's going on here, but there is some discussion of the issue and a workaround here: https://github.com/dlenski/openconnect/issues/104

The workaround, in case you encounter this issue on a new install (I'm running 18.04 ubuntu) is, after your connection is active, look for the following process:

    run-parts --arg=-a --arg=tun0 /etc/resolvconf/update.d

Killing this will give you a working VPN connection.

**Comment by HenrikBengtsson** [comment]
From https://github.com/dlenski/openconnect/issues/104:

> I'll close this one as "not OpenConnect's fault" and point anyone else to this if it comes up again.
> 
> I hope Ubuntu will fix this soon.

which refers to [Ubuntu Bug #1752411: "bind9-host, avahi-daemon-check-dns.sh hang forever causes network connections to get stuck"](https://bugs.launchpad.net/ubuntu/+source/openconnect/+bug/1752411), which is still open and provides a few workaround (please look there, but if I run into this and finds a solid workaround among those, I'll comment here).

**Comment by patrickhwood** [comment]
I found that changing the /sbin/resolvconf line in modify_resolvconf_manager() in vpnc-script to 

`` echo "$NEW_RESOLVCONF" | /sbin/resolvconf -a $TUNDEV &``

fixes it.

**Comment by patrickhwood** [comment]
I downloaded an up-to-date version as suggested on the openconnect site: http://www.infradead.org/openconnect/vpnc-script.html and use it with the -s option.  There's also a vpnc-script in /usr/'share/vpnc-scripts, but I haven't tried that one, nor am I 100% certain it's the one used by openconnect by default.

The change was to simply add the "&" on the end of the line so it would run in the background and not stall the execution of the script (which seems to be the cause of the problem).

**Comment by chruck** [comment]
Reading the `vpnc-script` code, I discovered that if I append `resolve` to the `hosts` line in `/etc/nsswitch.conf`, it also works:
```
hosts:          files mdns4_minimal [NOTFOUND=return] dns resolve
```

**Comment by HenrikBengtsson** [comment]
Moot; the "General Support" for Ubuntu 18.04 LTS ended 2023-06 (https://en.wikipedia.org/wiki/Ubuntu#Releases).
