### ISSUE TITLE
ERROR: No internet connection on stop

### ISSUE THREAD

**Issue by RossBoylan** [HenrikBengtsson/ucsf-vpn#14]
I get an odd error message when I end my session.  I know VPN was active moments before because I had just used it, and I know my regular connection is active now because I'm using it.

As far as I can tell, the stop operation worked fine.  So, seemingly, a cosmetic issue.
```
ross@secure-stretch:~/src/ucsf-vpn$ bin/ucsf-vpn stop
[sudo] password for ross: 
RESULT: Killed local ('openconnect') VPN process
ERROR: No internet connection
RESULT: 
```

**Comment by HenrikBengtsson** [comment]
This has been solved in the develop branch, which include major improvements.  There are [few more things](https://github.com/HenrikBengtsson/ucsf-vpn/milestone/5) I want to try to address before release next version.
