### ISSUE TITLE
Generalize the command syntax

### ISSUE THREAD

**Issue by RossBoylan** [HenrikBengtsson/ucsf-vpn#16]
Currently specifying options as `--foo=stuff` does not work; it must be `--foo stuff`.  It would be nice if the script could deal with arguments in a more standard way.

Failing that, perhaps a more explicit warning in the documentation or while parsing the arguments, might help.

For example, I call ucsf-vpn with the argument `--token=6082911`.  That was passed on to openconnect, producing an error:

```shell
[DEBUG] call: sudo openconnect --script=/home/ross/src/ucsf-vpn/bin/selectiveTunnel --token=6082911 --juniper https://remote.ucsf.edu/pulse --background --user=rdboylan --passwd-on-stdin --quiet --authgroup="Dual-Factor Pulse Clients"
openconnect: option '--token=6082911' is ambiguous; possibilities: '--token-mode' '--token-secret'
```

Also, this seems to suggest the random unknown command arguments are passed to openconnect unchanged.  Is that true?  Is it desirable?

Replacing the = sign with a space worked properly.

**Comment by HenrikBengtsson** [comment]
Fixed in the develop branch.  Will be part of the next release.
