### ISSUE TITLE
ucsf-vpn does not prompt for the second password.

### ISSUE THREAD

**Issue by akemisetti** [HenrikBengtsson/ucsf-vpn#30]
I am providing correct password. It will wait for few mins after the UCSF password and then errors out. Here is the complete stack.

ubuntu1:~/ucsf-vpn$ ./ucsf-vpn start --token=push --user=xxxx  --verbose
INFO: Pinging '8.8.8.8' once
INFO: Verified that internet connection works
INFO: Getting public IP (from https://ipinfo.io/ip)
INFO: Pinging '8.8.8.8' once
INFO: Preparing to connect to VPN server 'remote.ucsf.edu'
WARNING: This action ('ucsf-vpn start') requires administrative ("sudo") rights.
Enter the password for your account ('xxxxxxxx') on your local computer ('ubuntu1'): 
INFO: Administrative ("sudo") rights establish
Enter your UCSF Active Directory password: <password>
INFO: Connecting to VPN server 'remote.ucsf.edu'
WARNING: Juniper Network Connect support is experimental.
It will probably be superseded by Junos Pulse support
Failed to connect to host remote.ucsf.edu
Failed to open HTTPS connection to remote.ucsf.edu
Failed to obtain WebVPN cookie
ERROR: Failed to connect to VPN server (no running OpenConnect process). Check your username, password, and token.

Please help

Thanks
Anil

**Comment by HenrikBengtsson** [comment]
Version of Ubuntu and version of openconnect?

**Comment by HenrikBengtsson** [comment]
Ah... now I realize.  It might just be that you misunderstood what `--token=push` does?  From `ucsf-vpn --help` we have:
```
Options:
 --token=<token>  One-time two-factor authentication (2FA) token or method:
                   - 'prompt' (user is prompted to enter the token),
                   - 'push' ("approve and confirm" in Duo app; default),
                   - 'phone' (receive phone call and "press any key"),
                   - 'sms' (receive code via text message),
                   -  6 or 7 digit token (from Duo app), or
                   -  44-letter YubiKey token ("press YubiKey")
```

If you'd like to enter a "pin", then use `--token=prompt`.  If you use `--token=push`, then you should accept the request in the Duo app on your smartphone.  I've created feature request #31 to clarify this.

**Comment by HenrikBengtsson** [comment]
@akemisetti, I haven't heard back from on this one so I'm closing.  Feel free to reopen if needed.
