### ISSUE TITLE
sudo warnings in logs

### ISSUE THREAD

**Issue by RossBoylan** [HenrikBengtsson/ucsf-vpn#37]
Since upgrading to the current (actually, development) code my logs are showing repeated notices from sudo that "a password is required" for me.  The message indicates `PWD` is my ucsf-vpn directory.

It's true a password is required, but the old code wasn't producing log messages that were getting flagged.

There may not be anything  particularly wrong with the current behavior.  I noticed it because my automatic log-scanning software, logcheck, picks up these messages as "Security Events" indicating a moderate level of risk.  I do not usually get reports with such severity.

I can just ignore the messages, or even add a pattern that will make logcheck ignore the messages.

Guess: the old code always prompted for a password, while the new code tries to `sudo` in hopes there will still be a password cached (I think the release notes mentioned this)?  And if it isn't, it triggers the warning in the logs and the request to enter a password?

If there's a way to check if the password is cached without triggering the warning, that would be great.  Quick search suggests (https://unix.stackexchange.com/questions/115506/sudo-testing-for-credentials) checking the return status of `sudo -nv 2> /dev/null` to tell if pasword-free `sudo` works, but I suspect that would trigger the same warning.  A workaround might be to check for the cache file, which seems to be `/var/run/sudo/ross` for me but that's likely system dependent (`/var/lib/sudo` is mentioned elsewhere) and would still require figuring out if the validity interval had passed (unless it is reliably deleted when it is too old.  I see a  file from 28 minutes ago, and so I don't think it is deleted when it expires)

Maybe PAM provides some tools that would help.  I'm not that familiar with it, but I assume it has a role in all this.

Even `sudo -ls` require credentials, and so I suspect it is hard to use `sudo` to test for credentials without triggering attempts to elevate.  The `-n` option above, for non-interactive, suppresses the prompt, but that doesn't necessarily mean it suppresses the failure report.

**Comment by HenrikBengtsson** [comment]
I think I understand. Would mind sharing one of those log entries?

Also, exactly what is `PWD`?  The shell defines that but it could mean "password"?

**Comment by HenrikBengtsson** [comment]
Forgot to say: yes, I changed to use a dummy `sudo` up front (to get an early error if not available) and then rely on "cached" sudo.

**Comment by RossBoylan** [comment]
Reported by logcheck from auth.log:
```
barley.betterworld.us : Jun 21 02:03:04 : ross : a password is required ; TTY=pts/4 ; PWD=/home/ross/src/ucsf-vpn/bin ; USER=root ; COMMAND=validate
```
WD must be working directory; not sure about P: process? present?

I gather from reading about sudo that the caching of passwords can be disabled, and so in principle might not work.

**Comment by HenrikBengtsson** [comment]
> WD must be working directory; not sure about P: process? present?

Sorry, for not being clear. I didn't understand why you mentioned `PWD` at all, but seeing the log entry I understand you just paraphrased the log entry.  Unless you mean `PWD` is important in somehow(?)

> I gather from reading about sudo that the caching of passwords can be disabled, and so in principle might not work.

Yes, thought about that after you posted this issue.  If that's the case, then you'll have to enter it one time for no good reason.  It would be neat figure out if it can be cached.

**Comment by RossBoylan** [comment]
Actually, I get a report from logcheck and from somewhere else.  The "somewhere else" sends an email as soon as the event happens, with email flagged as important.  I don't see anything else about it in the conventional or systemd logs.

**Comment by RossBoylan** [comment]
> > WD must be working directory; not sure about P: process? present?
> 
> Sorry, for not being clear. I didn't understand why you mentioned `PWD` at all, but seeing the log entry I understand you just paraphrased the log entry. Unless you mean `PWD` is important in somehow(?)

Your question was clear.  I was simply repeating what was in the log.  The only significance is that it clarifies that message is coming from `ucsf-vpn` (albeit indirectly) rather than from something else, in which case it wouldn't be a `ucsf-vpn` issue at all.

Aside: As I move between languages, I find remembering how to refer to the current working directory is one of the points I'm most likely to get wrong: `cwd`, `pwd`, `wd`, `getwd`, `get_wd`, .....  I wish it were more standardized, but that ship has sailed.

**Comment by HenrikBengtsson** [comment]
> If there's a way to check if the password is cached without triggering the warning, that would be great. Quick search suggests (https://unix.stackexchange.com/questions/115506/sudo-testing-for-credentials) checking the return status of sudo -nv 2> /dev/null to tell if pasword-free sudo works, but I suspect that would trigger the same warning.

This is already done;

https://github.com/HenrikBengtsson/ucsf-vpn/blob/62c846dc6879c09b7282c2f56bdef779087844ff/bin/ucsf-vpn#L251-L254

(I see that there's some TAB <-> SPACEs issues in the code)

**Comment by RossBoylan** [comment]
I can confirm that executing `sudo -v -n` in a terminal results in the warning in `auth.log` quoted above and the immediate email.

**Comment by HenrikBengtsson** [comment]
> I can confirm that executing sudo -v -n in a terminal results in the warning in auth.log quoted above and the immediate email.

And you're saying a regular `sudo` does not trigger such a warning?

**Comment by RossBoylan** [comment]
It does not; in particular `sudo -i` followed by my entering the correct password does not.  I just tried it.

I wasn't saying that in my original post, but in retrospect it seems clear, since I've been doing regular `sudo` either directly or through the old `ucsf-vpn` without getting the warning.

**Comment by HenrikBengtsson** [comment]
I guess one option is to add a command line option `--pre-sudo=false` and environment variable `USCF_VPN_PRE_SUDO=false` to skip the up-front caching of sudo and just rely on having to enter it wherever/whenever `sudo` is used.

**Comment by RossBoylan** [comment]
This is getting beyond the original issue, but if we're adding options, how about one that skips `sudo` if the script is run as `root`?  It wouldn't really need to be an option; the code could just check if it's already `root`.  Maybe it does already; I haven't tried it.  It doesn't look as if there's any check in the current code.

Unless you want to discourage that scenario.

My impression is that  Linux has acquired quite a range of security mechanisms, so that a simple check of the effective user ID may be neither necessary nor sufficient in all cases.  And there may be a lot of cases.  Off the top of my head systems that might be involved include `SELinux`, `packagekit`, `PAM` and `systemd`.  Because now everything involves `systemd` :stuck_out_tongue_closed_eyes:.

**Comment by HenrikBengtsson** [comment]
Try it; I think sudo on a script that calls sudo inside will moot the inner sudo:s.

The original reason for using sudo inside the script is that the script also supports the Pulse client, which doesn't need sudo.

**Comment by RossBoylan** [comment]
The results of invoking the script as `root` are mostly positive.  There were a few glitches:
 1. On my initial run it started asking for id info.  Solved by creating a symlink in `/root` to `.netrc` in my home directory.
 2. 2nd try did succeed, but it reported the following error:
```
NOTE: Open the Duo Mobile app on your smartphone or tablet to confirm ...
OK: OpenConnect status: 'openconnect' process running (PID=28075)
DEBUG: running list-records in /etc/resolvconf/run/interface: enp5s0.inet
lo.named
tun0
ERROR: Public IP information: ip=66.181.128.6, hostname=m128-6.dsl.rawbw.com, org=AS7961 Raw Bandwidth Communications, Inc. [ucsf-vpn 5.2.0-9000, OpenConnect 8.02-1+deb10u1]
```
The last line looks  as if it thinks I am not on the intranet, since the info shown is correct if `ipinfo.io` is contacted without using the intranet.  But I am on the intranet, including the routing for the ping server `ipinfo.io` through the intranet.  I double-checked the current IPs for ipinfo.io.  And
```
# ~ross/src/ucsf-vpn/bin/ucsf-vpn status
OpenConnect status: 'openconnect' process running (PID=28075)
Public IP information: ip=128.218.42.252, hostname=, org=AS5653 University of California San Francisco
Connected to the VPN
```
so even `ucsf-vpn` seems to agree things are good.

Maybe there is a race in my existing code and sometimes the connection test happens before the routing changes have taken effect.  I don't know if the second problem was induced by running as `root` or if it just happened to take place then.

Positively,
 1. I did end up connected.
 2. Did not need to enter my local password again.
 3. No "password is required" messages (or any other message) in my log files and no email alerts.

**Comment by HenrikBengtsson** [comment]
I've updated to support option `--presudo=false`, or equivalently env var `UCSF_VPN_PRESUDO=false`. This skips establishing 'sudo' permissions upfront;

```sh
$ bin/ucsf-vpn start --presudo=false
WARNING: If you are prompted '[sudo] password for alice:' below, please enter the password for your account ('henrik') on your local computer ('hb-x1-2023')
Enter 'push' (default), 'phone', 'sms', a 6 or 7 digit token, or press your YubiKey: 
[sudo] password for alice: 
```
